apiVersion: v1
kind: Namespace
metadata:
  name: vault-platform
  labels:
    name: vault-platform
    environment: production
    app: vault-modernization
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: vault-platform-quota
  namespace: vault-platform
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "50"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: vault-platform-limits
  namespace: vault-platform
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
  - default:
      cpu: 1
      memory: 1Gi
    defaultRequest:
      cpu: 200m
      memory: 256Mi
    type: Pod 