apiVersion: v1
kind: Secret
metadata:
  name: vault-platform-secrets
  namespace: vault-platform
type: Opaque
data:
  # Database Secrets (base64 encoded)
  POSTGRES_PASSWORD: dmF1bHRwYXNz  # vaultpass
  POSTGRES_USER: dmF1bHQ=  # vault
  POSTGRES_DB: dmF1bHQ=  # vault
  
  # Redis Secrets
  REDIS_PASSWORD: cmVkaXNwYXNz  # redispass
  
  # JWT Secrets (should be changed in production)
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==  # your-super-secret-jwt-key-change-in-production
  
  # API Keys (placeholder - should be replaced with real keys)
  AMAZON_API_KEY: cGxhY2Vob2xkZXItYW1hem9uLWFwaS1rZXk=  # placeholder-amazon-api-key
  WALMART_API_KEY: cGxhY2Vob2xkZXItd2FsbWFydC1hcGkta2V5  # placeholder-walmart-api-key
  EBAY_API_KEY: cGxhY2Vob2xkZXItZWJheS1hcGkta2V5  # placeholder-ebay-api-key
  
  # Vendor API Keys
  INGRAM_API_KEY: cGxhY2Vob2xkZXItaW5ncmFtLWFwaS1rZXk=  # placeholder-ingram-api-key
  TD_SYNNEX_API_KEY: cGxhY2Vob2xkZXItdGQtc3lubmV4LWFwaS1rZXk=  # placeholder-td-synnex-api-key
  DH_API_KEY: cGxhY2Vob2xkZXItZGgtYXBpLWtleQ==  # placeholder-dh-api-key
  
  # Email Service Secrets
  SMTP_HOST: c21hcC5nbWFpbC5jb20=  # smtp.gmail.com
  SMTP_PORT: NTg3  # 587
  SMTP_USER: cGxhY2Vob2xkZXItZW1haWxAZ21haWwuY29t  # placeholder-email@gmail.com
  SMTP_PASSWORD: cGxhY2Vob2xkZXItcGFzc3dvcmQ=  # placeholder-password
  
  # Monitoring Secrets
  PROMETHEUS_PASSWORD: cHJvbWV0aGV1cy1wYXNzd29yZA==  # prometheus-password
  GRAFANA_PASSWORD: Z3JhZmFuYS1wYXNzd29yZA==  # grafana-password
  
  # SSL/TLS Certificates (placeholder)
  SSL_CERT: cGxhY2Vob2xkZXItc3NsLWNlcnQ=  # placeholder-ssl-cert
  SSL_KEY: cGxhY2Vob2xkZXItc3NsLWtleQ==  # placeholder-ssl-key 